// Mocks generated by Mockito 5.0.16 from annotations
// in twilio_conversations/example/ios/.symlinks/plugins/twilio_conversations/test/twilio_conversations_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:twilio_conversations/api.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeConversationClientData_0 extends _i1.Fake
    implements _i2.ConversationClientData {}

/// A class which mocks [PluginApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPluginApi extends _i1.Mock implements _i2.PluginApi {
  MockPluginApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> debug(bool? arg_enableNative, bool? arg_enableSdk) =>
      (super.noSuchMethod(
          Invocation.method(#debug, [arg_enableNative, arg_enableSdk]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<_i2.ConversationClientData> create(
          String? arg_jwtToken, _i2.PropertiesData? arg_properties) =>
      (super.noSuchMethod(
              Invocation.method(#create, [arg_jwtToken, arg_properties]),
              returnValue: Future<_i2.ConversationClientData>.value(
                  _FakeConversationClientData_0()))
          as _i3.Future<_i2.ConversationClientData>);
  @override
  String toString() => super.toString();
}
