// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class TWCONConversationClientData;
@class TWCONPropertiesData;
@class TWCONConversationData;
@class TWCONAttributesData;
@class TWCONTokenData;
@class TWCONMessageMediaData;
@class TWCONMessageData;
@class TWCONMessageOptionsData;
@class TWCONParticipantData;
@class TWCONDeliveryReceiptData;
@class TWCONDetailedDeliveryReceiptData;
@class TWCONUserData;
@class TWCONMessageCount;
@class TWCONConversationUpdatedData;
@class TWCONErrorInfoData;

@interface TWCONConversationClientData : NSObject
+ (instancetype)makeWithMyIdentity:(nullable NSString *)myIdentity
    connectionState:(nullable NSString *)connectionState
    isReachabilityEnabled:(nullable NSNumber *)isReachabilityEnabled;
@property(nonatomic, copy, nullable) NSString * myIdentity;
@property(nonatomic, copy, nullable) NSString * connectionState;
@property(nonatomic, strong, nullable) NSNumber * isReachabilityEnabled;
@end

@interface TWCONPropertiesData : NSObject
+ (instancetype)makeWithRegion:(nullable NSString *)region;
@property(nonatomic, copy, nullable) NSString * region;
@end

@interface TWCONConversationData : NSObject
+ (instancetype)makeWithSid:(nullable NSString *)sid
    attributes:(nullable TWCONAttributesData *)attributes
    uniqueName:(nullable NSString *)uniqueName
    friendlyName:(nullable NSString *)friendlyName
    status:(nullable NSString *)status
    synchronizationStatus:(nullable NSString *)synchronizationStatus
    dateCreated:(nullable NSString *)dateCreated
    createdBy:(nullable NSString *)createdBy
    dateUpdated:(nullable NSString *)dateUpdated
    lastMessageDate:(nullable NSString *)lastMessageDate
    lastReadMessageIndex:(nullable NSNumber *)lastReadMessageIndex
    lastMessageIndex:(nullable NSNumber *)lastMessageIndex;
@property(nonatomic, copy, nullable) NSString * sid;
@property(nonatomic, strong, nullable) TWCONAttributesData * attributes;
@property(nonatomic, copy, nullable) NSString * uniqueName;
@property(nonatomic, copy, nullable) NSString * friendlyName;
@property(nonatomic, copy, nullable) NSString * status;
@property(nonatomic, copy, nullable) NSString * synchronizationStatus;
@property(nonatomic, copy, nullable) NSString * dateCreated;
@property(nonatomic, copy, nullable) NSString * createdBy;
@property(nonatomic, copy, nullable) NSString * dateUpdated;
@property(nonatomic, copy, nullable) NSString * lastMessageDate;
@property(nonatomic, strong, nullable) NSNumber * lastReadMessageIndex;
@property(nonatomic, strong, nullable) NSNumber * lastMessageIndex;
@end

@interface TWCONAttributesData : NSObject
+ (instancetype)makeWithType:(nullable NSString *)type
    data:(nullable NSString *)data;
@property(nonatomic, copy, nullable) NSString * type;
@property(nonatomic, copy, nullable) NSString * data;
@end

@interface TWCONTokenData : NSObject
+ (instancetype)makeWithToken:(nullable NSString *)token;
@property(nonatomic, copy, nullable) NSString * token;
@end

@interface TWCONMessageMediaData : NSObject
+ (instancetype)makeWithSid:(nullable NSString *)sid
    fileName:(nullable NSString *)fileName
    type:(nullable NSString *)type
    size:(nullable NSNumber *)size
    conversationSid:(nullable NSString *)conversationSid
    messageSid:(nullable NSString *)messageSid
    messageIndex:(nullable NSNumber *)messageIndex;
@property(nonatomic, copy, nullable) NSString * sid;
@property(nonatomic, copy, nullable) NSString * fileName;
@property(nonatomic, copy, nullable) NSString * type;
@property(nonatomic, strong, nullable) NSNumber * size;
@property(nonatomic, copy, nullable) NSString * conversationSid;
@property(nonatomic, copy, nullable) NSString * messageSid;
@property(nonatomic, strong, nullable) NSNumber * messageIndex;
@end

@interface TWCONMessageData : NSObject
+ (instancetype)makeWithSid:(nullable NSString *)sid
    messageIndex:(nullable NSNumber *)messageIndex
    author:(nullable NSString *)author
    subject:(nullable NSString *)subject
    messageBody:(nullable NSString *)messageBody
    type:(nullable NSString *)type
    hasMedia:(nullable NSNumber *)hasMedia
    media:(nullable TWCONMessageMediaData *)media
    conversationSid:(nullable NSString *)conversationSid
    participantSid:(nullable NSString *)participantSid
    dateCreated:(nullable NSString *)dateCreated
    dateUpdated:(nullable NSString *)dateUpdated
    lastUpdatedBy:(nullable NSString *)lastUpdatedBy
    attributes:(nullable TWCONAttributesData *)attributes;
@property(nonatomic, copy, nullable) NSString * sid;
@property(nonatomic, strong, nullable) NSNumber * messageIndex;
@property(nonatomic, copy, nullable) NSString * author;
@property(nonatomic, copy, nullable) NSString * subject;
@property(nonatomic, copy, nullable) NSString * messageBody;
@property(nonatomic, copy, nullable) NSString * type;
@property(nonatomic, strong, nullable) NSNumber * hasMedia;
@property(nonatomic, strong, nullable) TWCONMessageMediaData * media;
@property(nonatomic, copy, nullable) NSString * conversationSid;
@property(nonatomic, copy, nullable) NSString * participantSid;
@property(nonatomic, copy, nullable) NSString * dateCreated;
@property(nonatomic, copy, nullable) NSString * dateUpdated;
@property(nonatomic, copy, nullable) NSString * lastUpdatedBy;
@property(nonatomic, strong, nullable) TWCONAttributesData * attributes;
@end

@interface TWCONMessageOptionsData : NSObject
+ (instancetype)makeWithBody:(nullable NSString *)body
    attributes:(nullable TWCONAttributesData *)attributes
    mimeType:(nullable NSString *)mimeType
    filename:(nullable NSString *)filename
    inputPath:(nullable NSString *)inputPath
    mediaProgressListenerId:(nullable NSNumber *)mediaProgressListenerId;
@property(nonatomic, copy, nullable) NSString * body;
@property(nonatomic, strong, nullable) TWCONAttributesData * attributes;
@property(nonatomic, copy, nullable) NSString * mimeType;
@property(nonatomic, copy, nullable) NSString * filename;
@property(nonatomic, copy, nullable) NSString * inputPath;
@property(nonatomic, strong, nullable) NSNumber * mediaProgressListenerId;
@end

@interface TWCONParticipantData : NSObject
+ (instancetype)makeWithSid:(nullable NSString *)sid
    conversationSid:(nullable NSString *)conversationSid
    type:(nullable NSString *)type
    attributes:(nullable TWCONAttributesData *)attributes
    dateCreated:(nullable NSString *)dateCreated
    dateUpdated:(nullable NSString *)dateUpdated
    identity:(nullable NSString *)identity
    lastReadMessageIndex:(nullable NSNumber *)lastReadMessageIndex
    lastReadTimestamp:(nullable NSString *)lastReadTimestamp;
@property(nonatomic, copy, nullable) NSString * sid;
@property(nonatomic, copy, nullable) NSString * conversationSid;
@property(nonatomic, copy, nullable) NSString * type;
@property(nonatomic, strong, nullable) TWCONAttributesData * attributes;
@property(nonatomic, copy, nullable) NSString * dateCreated;
@property(nonatomic, copy, nullable) NSString * dateUpdated;
@property(nonatomic, copy, nullable) NSString * identity;
@property(nonatomic, strong, nullable) NSNumber * lastReadMessageIndex;
@property(nonatomic, copy, nullable) NSString * lastReadTimestamp;
@end

@interface TWCONDeliveryReceiptData : NSObject
+ (instancetype)makeWithTotal:(nullable NSNumber *)total
    read:(nullable NSString *)read
    undelivered:(nullable NSString *)undelivered
    delivered:(nullable NSString *)delivered
    failed:(nullable NSString *)failed
    sent:(nullable NSString *)sent;
@property(nonatomic, strong, nullable) NSNumber * total;
@property(nonatomic, copy, nullable) NSString * read;
@property(nonatomic, copy, nullable) NSString * undelivered;
@property(nonatomic, copy, nullable) NSString * delivered;
@property(nonatomic, copy, nullable) NSString * failed;
@property(nonatomic, copy, nullable) NSString * sent;
@end

@interface TWCONDetailedDeliveryReceiptData : NSObject
+ (instancetype)makeWithConversationSid:(nullable NSString *)conversationSid
    channelMessageSid:(nullable NSString *)channelMessageSid
    dateCreatedAsDate:(nullable NSString *)dateCreatedAsDate
    dateUpdatedAsDate:(nullable NSString *)dateUpdatedAsDate
    errorCode:(nullable NSNumber *)errorCode
    messageSid:(nullable NSString *)messageSid
    participantSid:(nullable NSString *)participantSid
    sid:(nullable NSString *)sid;
@property(nonatomic, copy, nullable) NSString * conversationSid;
@property(nonatomic, copy, nullable) NSString * channelMessageSid;
@property(nonatomic, copy, nullable) NSString * dateCreatedAsDate;
@property(nonatomic, copy, nullable) NSString * dateUpdatedAsDate;
@property(nonatomic, strong, nullable) NSNumber * errorCode;
@property(nonatomic, copy, nullable) NSString * messageSid;
@property(nonatomic, copy, nullable) NSString * participantSid;
@property(nonatomic, copy, nullable) NSString * sid;
@end

@interface TWCONUserData : NSObject
+ (instancetype)makeWithIdentity:(nullable NSString *)identity
    attributes:(nullable TWCONAttributesData *)attributes
    friendlyName:(nullable NSString *)friendlyName
    isNotifiable:(nullable NSNumber *)isNotifiable
    isOnline:(nullable NSNumber *)isOnline
    isSubscribed:(nullable NSNumber *)isSubscribed;
@property(nonatomic, copy, nullable) NSString * identity;
@property(nonatomic, strong, nullable) TWCONAttributesData * attributes;
@property(nonatomic, copy, nullable) NSString * friendlyName;
@property(nonatomic, strong, nullable) NSNumber * isNotifiable;
@property(nonatomic, strong, nullable) NSNumber * isOnline;
@property(nonatomic, strong, nullable) NSNumber * isSubscribed;
@end

@interface TWCONMessageCount : NSObject
+ (instancetype)makeWithCount:(nullable NSNumber *)count;
@property(nonatomic, strong, nullable) NSNumber * count;
@end

@interface TWCONConversationUpdatedData : NSObject
+ (instancetype)makeWithConversation:(nullable TWCONConversationData *)conversation
    reason:(nullable NSString *)reason;
@property(nonatomic, strong, nullable) TWCONConversationData * conversation;
@property(nonatomic, copy, nullable) NSString * reason;
@end

@interface TWCONErrorInfoData : NSObject
+ (instancetype)makeWithCode:(nullable NSNumber *)code
    message:(nullable NSString *)message
    status:(nullable NSNumber *)status;
@property(nonatomic, strong, nullable) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, strong, nullable) NSNumber * status;
@end

/// The codec used by TWCONPluginApi.
NSObject<FlutterMessageCodec> *TWCONPluginApiGetCodec(void);

@protocol TWCONPluginApi
- (void)debugEnableNative:(NSNumber *)enableNative enableSdk:(NSNumber *)enableSdk error:(FlutterError *_Nullable *_Nonnull)error;
- (void)createJwtToken:(NSString *)jwtToken properties:(TWCONPropertiesData *)properties completion:(void (^)(TWCONConversationClientData *_Nullable, FlutterError *_Nullable))completion;
@end

extern void TWCONPluginApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<TWCONPluginApi> *_Nullable api);

/// The codec used by TWCONConversationClientApi.
NSObject<FlutterMessageCodec> *TWCONConversationClientApiGetCodec(void);

@protocol TWCONConversationClientApi
- (void)updateTokenToken:(NSString *)token completion:(void (^)(FlutterError *_Nullable))completion;
- (void)shutdownWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)createConversationFriendlyName:(NSString *)friendlyName completion:(void (^)(TWCONConversationData *_Nullable, FlutterError *_Nullable))completion;
- (void)getMyConversationsWithCompletion:(void (^)(NSArray<TWCONConversationData *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getConversationConversationSidOrUniqueName:(NSString *)conversationSidOrUniqueName completion:(void (^)(TWCONConversationData *_Nullable, FlutterError *_Nullable))completion;
- (void)getMyUserWithCompletion:(void (^)(TWCONUserData *_Nullable, FlutterError *_Nullable))completion;
- (void)registerForNotificationTokenData:(TWCONTokenData *)tokenData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)unregisterForNotificationTokenData:(TWCONTokenData *)tokenData completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void TWCONConversationClientApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<TWCONConversationClientApi> *_Nullable api);

/// The codec used by TWCONConversationApi.
NSObject<FlutterMessageCodec> *TWCONConversationApiGetCodec(void);

@protocol TWCONConversationApi
- (void)joinConversationSid:(NSString *)conversationSid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)leaveConversationSid:(NSString *)conversationSid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)destroyConversationSid:(NSString *)conversationSid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)typingConversationSid:(NSString *)conversationSid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)sendMessageConversationSid:(NSString *)conversationSid options:(TWCONMessageOptionsData *)options completion:(void (^)(TWCONMessageData *_Nullable, FlutterError *_Nullable))completion;
- (void)addParticipantByIdentityConversationSid:(NSString *)conversationSid identity:(NSString *)identity completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)removeParticipantConversationSid:(NSString *)conversationSid participantSid:(NSString *)participantSid completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)removeParticipantByIdentityConversationSid:(NSString *)conversationSid identity:(NSString *)identity completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)getParticipantByIdentityConversationSid:(NSString *)conversationSid identity:(NSString *)identity completion:(void (^)(TWCONParticipantData *_Nullable, FlutterError *_Nullable))completion;
- (void)getParticipantBySidConversationSid:(NSString *)conversationSid participantSid:(NSString *)participantSid completion:(void (^)(TWCONParticipantData *_Nullable, FlutterError *_Nullable))completion;
- (void)getParticipantsListConversationSid:(NSString *)conversationSid completion:(void (^)(NSArray<TWCONParticipantData *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getMessagesCountConversationSid:(NSString *)conversationSid completion:(void (^)(TWCONMessageCount *_Nullable, FlutterError *_Nullable))completion;
- (void)getUnreadMessagesCountConversationSid:(NSString *)conversationSid completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)advanceLastReadMessageIndexConversationSid:(NSString *)conversationSid lastReadMessageIndex:(NSNumber *)lastReadMessageIndex completion:(void (^)(TWCONMessageCount *_Nullable, FlutterError *_Nullable))completion;
- (void)setLastReadMessageIndexConversationSid:(NSString *)conversationSid lastReadMessageIndex:(NSNumber *)lastReadMessageIndex completion:(void (^)(TWCONMessageCount *_Nullable, FlutterError *_Nullable))completion;
- (void)setAllMessagesReadConversationSid:(NSString *)conversationSid completion:(void (^)(TWCONMessageCount *_Nullable, FlutterError *_Nullable))completion;
- (void)setAllMessagesUnreadConversationSid:(NSString *)conversationSid completion:(void (^)(TWCONMessageCount *_Nullable, FlutterError *_Nullable))completion;
- (void)getParticipantsCountConversationSid:(NSString *)conversationSid completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)getMessagesAfterConversationSid:(NSString *)conversationSid index:(NSNumber *)index count:(NSNumber *)count completion:(void (^)(NSArray<TWCONMessageData *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getMessagesBeforeConversationSid:(NSString *)conversationSid index:(NSNumber *)index count:(NSNumber *)count completion:(void (^)(NSArray<TWCONMessageData *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getMessageByIndexConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(TWCONMessageData *_Nullable, FlutterError *_Nullable))completion;
- (void)getLastMessagesConversationSid:(NSString *)conversationSid count:(NSNumber *)count completion:(void (^)(NSArray<TWCONMessageData *> *_Nullable, FlutterError *_Nullable))completion;
- (void)removeMessageConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)setAttributesConversationSid:(NSString *)conversationSid attributes:(TWCONAttributesData *)attributes completion:(void (^)(FlutterError *_Nullable))completion;
- (void)setFriendlyNameConversationSid:(NSString *)conversationSid friendlyName:(NSString *)friendlyName completion:(void (^)(FlutterError *_Nullable))completion;
- (void)setNotificationLevelConversationSid:(NSString *)conversationSid notificationLevel:(NSString *)notificationLevel completion:(void (^)(FlutterError *_Nullable))completion;
- (void)setUniqueNameConversationSid:(NSString *)conversationSid uniqueName:(NSString *)uniqueName completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void TWCONConversationApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<TWCONConversationApi> *_Nullable api);

/// The codec used by TWCONParticipantApi.
NSObject<FlutterMessageCodec> *TWCONParticipantApiGetCodec(void);

@protocol TWCONParticipantApi
- (void)getUserConversationSid:(NSString *)conversationSid participantSid:(NSString *)participantSid completion:(void (^)(TWCONUserData *_Nullable, FlutterError *_Nullable))completion;
- (void)setAttributesConversationSid:(NSString *)conversationSid participantSid:(NSString *)participantSid attributes:(TWCONAttributesData *)attributes completion:(void (^)(FlutterError *_Nullable))completion;
- (void)removeConversationSid:(NSString *)conversationSid participantSid:(NSString *)participantSid completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void TWCONParticipantApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<TWCONParticipantApi> *_Nullable api);

/// The codec used by TWCONMessageApi.
NSObject<FlutterMessageCodec> *TWCONMessageApiGetCodec(void);

@protocol TWCONMessageApi
- (void)getMediaContentTemporaryUrlConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)getParticipantConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(TWCONParticipantData *_Nullable, FlutterError *_Nullable))completion;
- (void)setAttributesConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex attributes:(TWCONAttributesData *)attributes completion:(void (^)(FlutterError *_Nullable))completion;
- (void)updateMessageBodyConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex messageBody:(NSString *)messageBody completion:(void (^)(FlutterError *_Nullable))completion;
- (void)getAggregatedDeliveryReceiptConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(TWCONDeliveryReceiptData *_Nullable, FlutterError *_Nullable))completion;
- (void)getDetailedDeliveryReceiptListConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(NSArray<TWCONDetailedDeliveryReceiptData *> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void TWCONMessageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<TWCONMessageApi> *_Nullable api);

/// The codec used by TWCONUserApi.
NSObject<FlutterMessageCodec> *TWCONUserApiGetCodec(void);

@protocol TWCONUserApi
- (void)setFriendlyNameIdentity:(NSString *)identity friendlyName:(NSString *)friendlyName completion:(void (^)(FlutterError *_Nullable))completion;
- (void)setAttributesIdentity:(NSString *)identity attributes:(TWCONAttributesData *)attributes completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void TWCONUserApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<TWCONUserApi> *_Nullable api);

/// The codec used by TWCONFlutterConversationClientApi.
NSObject<FlutterMessageCodec> *TWCONFlutterConversationClientApiGetCodec(void);

@interface TWCONFlutterConversationClientApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)errorErrorInfoData:(TWCONErrorInfoData *)errorInfoData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)conversationAddedConversationData:(TWCONConversationData *)conversationData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)conversationUpdatedEvent:(TWCONConversationUpdatedData *)event completion:(void (^)(FlutterError *_Nullable))completion;
- (void)conversationDeletedConversationData:(TWCONConversationData *)conversationData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)clientSynchronizationSynchronizationStatus:(NSString *)synchronizationStatus completion:(void (^)(FlutterError *_Nullable))completion;
- (void)conversationSynchronizationChangeConversationData:(TWCONConversationData *)conversationData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)connectionStateChangeConnectionState:(NSString *)connectionState completion:(void (^)(FlutterError *_Nullable))completion;
- (void)tokenAboutToExpireWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)tokenExpiredWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)userSubscribedUserData:(TWCONUserData *)userData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)userUnsubscribedUserData:(TWCONUserData *)userData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)userUpdatedUserData:(TWCONUserData *)userData reason:(NSString *)reason completion:(void (^)(FlutterError *_Nullable))completion;
- (void)addedToConversationNotificationConversationSid:(NSString *)conversationSid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)newMessageNotificationConversationSid:(NSString *)conversationSid messageIndex:(NSNumber *)messageIndex completion:(void (^)(FlutterError *_Nullable))completion;
- (void)notificationSubscribedWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)notificationFailedErrorInfoData:(TWCONErrorInfoData *)errorInfoData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)removedFromConversationNotificationConversationSid:(NSString *)conversationSid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)registeredWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)registrationFailedErrorInfoData:(TWCONErrorInfoData *)errorInfoData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)deregisteredWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)deregistrationFailedErrorInfoData:(TWCONErrorInfoData *)errorInfoData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)messageAddedConversationSid:(NSString *)conversationSid messageData:(TWCONMessageData *)messageData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)messageUpdatedConversationSid:(NSString *)conversationSid messageData:(TWCONMessageData *)messageData reason:(NSString *)reason completion:(void (^)(FlutterError *_Nullable))completion;
- (void)messageDeletedConversationSid:(NSString *)conversationSid messageData:(TWCONMessageData *)messageData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)participantAddedConversationSid:(NSString *)conversationSid participantData:(TWCONParticipantData *)participantData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)participantUpdatedConversationSid:(NSString *)conversationSid participantData:(TWCONParticipantData *)participantData reason:(NSString *)reason completion:(void (^)(FlutterError *_Nullable))completion;
- (void)participantDeletedConversationSid:(NSString *)conversationSid participantData:(TWCONParticipantData *)participantData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)typingStartedConversationSid:(NSString *)conversationSid conversationData:(TWCONConversationData *)conversationData participantData:(TWCONParticipantData *)participantData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)typingEndedConversationSid:(NSString *)conversationSid conversationData:(TWCONConversationData *)conversationData participantData:(TWCONParticipantData *)participantData completion:(void (^)(FlutterError *_Nullable))completion;
- (void)synchronizationChangedConversationSid:(NSString *)conversationSid conversationData:(TWCONConversationData *)conversationData completion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by TWCONFlutterLoggingApi.
NSObject<FlutterMessageCodec> *TWCONFlutterLoggingApiGetCodec(void);

@interface TWCONFlutterLoggingApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)logFromHostMsg:(NSString *)msg completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
